### ISSUE TITLE
Use async/await

### ISSUE THREAD

**Issue by TomoyaK** [ashift/etude#7]
## 概要

もし非同期処理がashiftの開発で必要となる見込みの場合、async/awaitで書いていくのが良さそうでしょうか？そうであれば、（@TomoyaKの学習のために）実行サンプルの作成をお願いします。

## タスク

* [ ] routes/async-sample.jsの追加
* [ ] views/async-sample.ejsの追加
* [ ] app.jsの編集

## 備考

- [Promiseとasync/awaitでJavaScriptの非同期処理をシンプルに記述する](https://sbfl.net/blog/2016/07/13/simplifying-async-code-with-promise-and-async-await/)
- [ES2017の新機能「async / await」でPromise（非同期処理）をスッキリ書く](https://mae.chab.in/archives/59793)
- [async/await入門 - async/awaitとは | CodeGrid](https://app.codegrid.net/entry/2017-async-await-1)

**Comment by shin-sforzando** [comment]
何を非同期処理にすれば良いですか？

**Comment by TomoyaK** [comment]
すみません。こちらは引き下げます。

**Comment by TomoyaK** [comment]
引き下げ理由は、Slackでのコメントが的確なので、以下に引用させてください。

> コメント欄にも書きましたが「何を非同期的に書けば良いかわからない」って根源的な問題はさておき、
Issueの目標が「鹿島田さんがasync/awaitを書けるようになる」なら、鹿島田さんが書かないとダメですよね。
言い換えれば、僕が仮にサンプルコードを書いたとして、書けない状態の鹿島田さんは正しいか判断できないのでApproveすることができないはずです。 
仮になんでも良いからサンプルコードが欲しい、ならばまだしも学習用のサンプルコードなら「何が達成されていればApproveされるのか」を書かないといけません。
そして、async/awaitは現行jsの標準構文なので、言わば「for文のサンプルを書け」みたいなお題なんですよ。
「いや、それは公式ドキュメントに一番詳しく書いてあるがな…」って話ですし、
その他の記法と排他的でもないので、async書けないならPromiseで書けば良いし、時と場合によってはsetTimeoutで書く方がわかりやすいこともあるのです。
「この場合はfor文よりwhile文の方が良いな」みたいな話です。
