### ISSUE TITLE
Set a favicon

### ISSUE THREAD

**Issue by TomoyaK** [ashift/etude#8]
## 概要

ashiftのロゴがfaviconとして表示されるようにしてください。
![ashift_logo3_500px](https://user-images.githubusercontent.com/7834783/39663268-22990f68-50ab-11e8-9c9c-e95241ef3026.png)

## タスク

* [ ] favicon.icoの用意およびアップロード
* [ ] app.jsの編集

## 備考

- .icoに変換してくれるWebサービス -> http://www.xiconeditor.com
- https://stackoverflow.com/questions/15463199/how-to-set-custom-favicon-in-express

**Comment by shin-sforzando** [comment]
1からicoを作る場合はxiconeditorも良いと思ったんですが、今回はpng→icoの変換だったので、
https://www.favicon-generator.org
を使いました。
Android用、iOS用も作ってくれて、設定ファイルまで揃えてくれるので便利だと思います。

**Comment by TomoyaK** [comment]
ico変換のサービスについて了解です。参考になります。ありがとうございます。
